### ISSUE TITLE
当加载的图片很多的时候,在选择图片界面直接点击图片预览时,程序奔溃

### ISSUE THREAD

**Issue by SwordSware** [ioneday/ImageSelector#20]
当加载的图片很多(如所有图片,超过6000多张)的时候,在选择图片界面直接点击图片预览时,程序奔溃,报错信息如下:
FATAL EXCEPTION: main
                                                                    Process: com.lanqian.skxcpt, PID: 13174
                                                                    java.lang.RuntimeException: Failure from system
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1516)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3993)
                                                                        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3954)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
                                                                        at com.yongchun.library.view.ImagePreviewActivity.startPreview(ImagePreviewActivity.java:63)
                                                                        at com.yongchun.library.view.ImageSelectorActivity.startPreview(ImageSelectorActivity.java:269)
                                                                        at com.yongchun.library.view.ImageSelectorActivity$4.onPictureClick(ImageSelectorActivity.java:189)
                                                                        at com.yongchun.library.adapter.ImageListAdapter$3.onClick(ImageListAdapter.java:124)
                                                                        at android.view.View.performClick(View.java:5207)
                                                                        at android.view.View$PerformClick.run(View.java:21177)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                     Caused by: android.os.TransactionTooLargeException: data parcel size 1904920 bytes
                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                        at android.os.BinderProxy.transact(Binder.java:503)
                                                                        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2680)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3993) 
                                                                        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48) 
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75) 
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3954) 
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856) 
                                                                        at com.yongchun.library.view.ImagePreviewActivity.startPreview(ImagePreviewActivity.java:63) 
                                                                        at com.yongchun.library.view.ImageSelectorActivity.startPreview(ImageSelectorActivity.java:269) 
                                                                        at com.yongchun.library.view.ImageSelectorActivity$4.onPictureClick(ImageSelectorActivity.java:189) 
                                                                        at com.yongchun.library.adapter.ImageListAdapter$3.onClick(ImageListAdapter.java:124) 
                                                                        at android.view.View.performClick(View.java:5207) 
                                                                        at android.view.View$PerformClick.run(View.java:21177) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by mstbetter** [comment]
@SwordSware   我这边是加载到2000多张的时候  点击图片预览的时候会直接退出这个activity

**Comment by PeterXiaosa** [comment]
不知道是不是OOM内存溢出，你们可以查一下 我觉得有可能会发生这个问题
