### ISSUE TITLE
裁剪上传的时候提示dialog泄露报错

### ISSUE THREAD

**Issue by fuqile** [ioneday/ImageSelector#7]
通过这样调用界面
ImageSelectorActivity.start(PersonInfoActivity.this, 1, ImageSelectorActivity.MODE_SINGLE, true, true, true);
onActivityResult 回调的时候会报下面的异常，一开始以为是Fragment的问题，换到Activity中也一样

07-20 00:22:03.922 12846-12846/com.ixwork E/WindowManager: android.view.WindowLeaked: Activity com.yongchun.library.view.ImageCropActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{a5cff5a V.E...... R.....ID 0,0-1336,464} that was originally added here
                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:565)
                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                               at android.app.Dialog.show(Dialog.java:350)
                                                               at android.app.ProgressDialog.show(ProgressDialog.java:151)
                                                               at android.app.ProgressDialog.show(ProgressDialog.java:139)
                                                               at com.yongchun.library.view.ImageCropActivity$2.onClick(ImageCropActivity.java:108)
                                                               at android.view.View.performClick(View.java:5697)
                                                               at android.widget.TextView.performClick(TextView.java:10816)
                                                               at android.view.View$PerformClick.run(View.java:22526)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:158)
                                                               at android.app.ActivityThread.main(ActivityThread.java:7232)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by funfang** [comment]
+1
